#!/usr/bin/env bash

# LittleEye Agent Automatic Installer
# Installs Python dependencies, sets up configuration, runs baseline, and configures systemd.

set -e

# Default settings
REPO_URL="https://github.com/synaps3s/littleeye.git"
INSTALL_DIR="/opt/littleeye"
CONFIG_DIR="/etc/littleeye"
CONFIG_PATH="${CONFIG_DIR}/config.yaml"
DASHBOARD_URL=""
AGENT_TOKEN=""

# Print usage instructions
usage() {
    echo "Usage: $0 --url <dashboard-url> --token <agent-token> [--repo <repo-url>]"
    echo ""
    echo "Options:"
    echo "  -u, --url      URL of the central LittleEye dashboard (e.g. http://192.168.1.100:8000)"
    echo "  -t, --token    Active authorization token created on the dashboard"
    echo "  -r, --repo     Custom GitHub repository URL (default: ${REPO_URL})"
    echo "  -h, --help     Show this help message"
    exit 1
}

# Parse command line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -u|--url) DASHBOARD_URL="$2"; shift ;;
        -t|--token) AGENT_TOKEN="$2"; shift ;;
        -r|--repo) REPO_URL="$2"; shift ;;
        -h|--help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
    shift
done

# Validate inputs
if [ -z "${DASHBOARD_URL}" ] || [ -z "${AGENT_TOKEN}" ]; then
    echo "Error: Both --url and --token arguments are required."
    usage
fi

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: Please run this script with sudo or as root."
    exit 1
fi

echo "========================================="
echo "Starting LittleEye Agent Setup..."
echo "========================================="

# 1. Install system prerequisites based on the package manager
echo "Checking and installing package dependencies..."
if [ -x "$(command -v apt-get)" ]; then
    apt-get update -qq
    apt-get install -y python3 python3-pip python3-venv git -y
elif [ -x "$(command -v dnf)" ]; then
    dnf install -y python3 python3-pip git -y
elif [ -x "$(command -v yum)" ]; then
    yum install -y python3 python3-pip git -y
else
    echo "Warning: No supported package manager found. Please ensure Python3, pip, venv, and git are installed."
fi

# 2. Clone/Update agent repository
if [ -d "${INSTALL_DIR}" ]; then
    echo "Directory ${INSTALL_DIR} already exists. Updating source code..."
    cd "${INSTALL_DIR}"
    if [ -d ".git" ]; then
        git pull
    else
        echo "Moving existing files to backup and cloning fresh repository..."
        mv "${INSTALL_DIR}" "${INSTALL_DIR}_backup_$(date +%s)"
        git clone "${REPO_URL}" "${INSTALL_DIR}"
    fi
else
    echo "Cloning source files from ${REPO_URL} to ${INSTALL_DIR}..."
    git clone "${REPO_URL}" "${INSTALL_DIR}"
fi

# 3. Create virtual environment and install packages
echo "Setting up python virtual environment..."
cd "${INSTALL_DIR}"
python3 -m venv venv
./venv/bin/pip install --upgrade pip
./venv/bin/pip install -r requirements.agent.txt

# 4. Generate configurations
echo "Writing configuration file to ${CONFIG_PATH}..."
mkdir -p "${CONFIG_DIR}"

cat <<EOF > "${CONFIG_PATH}"
# Generated by LittleEye installer
check_interval_minutes: 5
dashboard_url: "${DASHBOARD_URL}"
agent_token: "${AGENT_TOKEN}"
baseline_dir: "${INSTALL_DIR}/data/baselines"
report_dir: "${INSTALL_DIR}/data/reports"

severity_thresholds:
  files: "critical"
  sudo_users: "critical"
  ports: "warning"
  services: "warning"
  packages: "info"
  env_vars: "info"

watched_files:
  - "/etc/ssh/sshd_config"
  - "/etc/passwd"
  - "/etc/sudoers"
  - "/etc/hosts"
  - "/etc/fstab"
  - "/etc/crontab"
EOF

# 5. Initialize the baseline snapshot
echo "Taking system baseline snapshot..."
./venv/bin/python3 -m littleeye.agent.cli --config "${CONFIG_PATH}" init

# 6. Install systemd service
echo "Configuring background systemd service..."
cp "${INSTALL_DIR}/systemd/littleeye.service" "/etc/systemd/system/littleeye.service"
systemctl daemon-reload
systemctl enable --now littleeye

echo "========================================="
echo "LittleEye Agent Setup Completed Successfully!"
echo "The agent is running in the background and is checking for configuration drift."
echo "========================================="
